manager/urls.py
from django.urls import path,include
from manager import views

app_name = 'manager'

urlpatterns = [
    #Default and logged out views
    path("", views.index, name='index'),
    path("accounts/", include('django.contrib.auth.urls')),
    path("accounts/signup/", views.signup_page, name="signup"),
    #Views that should require login
    path("home", views.home, name='home'),
    path("profile", views.profile, name='profile'),
    path("edit_profile", views.edit_profile, name='edit_profile'),
    path("create_profile", views.create_profile, name='create_profile'),
    path("create_party", views.create_party, name='create_party'),
    path("create_corporation", views.create_corporation, name='create_corporation'),
    path("create_union", views.create_union, name='create_union'),
    path("create_paramilitary", views.create_paramilitary, name='create_paramilitary'),
    path("create_assignment", views.create_assignment, name='create_assignment'),
]

powermanager/urls.py
from django.contrib import admin,auth
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('manager.urls')),
]

manager/models.py
from django.db import models
from django.core import validators
from django.conf import settings

# Choices lists

country_choices = (
    ('US','America'),
    ('Malaysia','Malaysia'),
    ('Ukraine','Ukraine'),
    ('UK','Great Britain and Northern Ireland'),
    ('Kenya','Kenya'),
    ('Netherlands','Netherlands'),
    ('Canada','Canada'),
    ('Austria','Austria'),
    ('Germany','Germany'),
    ('Colombia','Colombia'),
    ('Israel','Israel'),
    ('Brazil','Brazil'),
    ('Indonesia','Indonesia'),
    ('Denmark','Denmark'),
    ('Italy','Italy'),
    ('Australia','Australia'),
    ('Greece','Greece'),
    ('Russia','Russian Federation'),
    ('Pakistan','Pakistan'),
    ('Nigeria','Nigeria'),
    ('China','China'),
    ('Poland','Poland'),
    ('Turkey','Turkey'),
    ('Japan','Japan'),
    ('Mexico','Mexico'),
    ('Sweden','Sweden'),
    ('India','India'),
    ('Philippines','Philippines'),
    ('N Korea',"The Democratic People's Republic of Korea"),
    ('Spain','Spain'),
    ('Ireland','Ireland'),
    ('Egypt','Egypt'),
    ('Argentina','Argentina'),
    ('S Korea','The Republic of Korea'),
    ('Iran','Iran'),
    ('France','French Republic'),
    ('Saudi Arabia','Saudi Arabia'),
    ('Syria','Syria'),
    ('NZ','New Zealand'),
) 

sector_types = (
    ('Agriculture','Agriculture'),
    ('Automobiles','Automobiles'),
    ('Defense','Defense'),
    ('Financial','Financial'),
    ('Healthcare','Healthcare'),
    ('Manufacturing','Manufacturing'),
    ('Media','Media'),
    ('Mining','Mining'),
    ('Oil and gas','Oil and gas'),
    ('Retail','Retail'),
    ('Technology','Technology'),
)

paramilitary_types = (
    ('Government','Government'),
    ('Crime','Crime'),
    ('Insurgent','Insurgent'),
)

# Create your models here.

#TODO enforce party/country

class Assignment(models.Model):
    name = models.CharField(max_length=100)
    content = models.CharField(max_length=5000)
    isDone = models.BooleanField(default=False)
    manager = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,related_name='given_assignments')
    def __str__(self):
        return f"""Assignment {self.id}: {self.name}:
        {self.content}
        Completed: {self.isDone}
        Manager: {self.manager}
        """

class Country(models.Model):
    name = models.CharField(max_length=100,choices=country_choices,unique=True)
    class Meta:
        verbose_name_plural = "Countries"
    def __str__(self):
        return f"{self.name}"

class Region(models.Model):
    country = models.ForeignKey('Country', on_delete=models.CASCADE,related_name='country_regions')
    name = models.CharField(max_length=100)
    def __str__(self):
        return f"{self.country}: {self.name}"

class Party(models.Model):
    name = models.CharField(max_length=40)
    country = models.ForeignKey('Country', on_delete=models.CASCADE,related_name='country_parties')
    class Meta:
        verbose_name_plural = "Parties"
    def __str__(self):
        return f"{self.name} party in {self.country}"

class Corporation(models.Model):
    name = models.CharField(max_length=40)
    specialization = models.CharField(max_length=50,choices=sector_types)
    def __str__(self):
        return f"{self.name}- {self.specialization} company"

class Union(models.Model):
    name = models.CharField(max_length=40)
    def __str__(self):
        return f"{self.name} Union"

class Sector(models.Model):
    type = models.CharField(max_length=50,choices=sector_types)
    region = models.ForeignKey('Region', on_delete=models.CASCADE,related_name='region_sectors')
    corporations = models.ForeignKey('Corporation', on_delete=models.CASCADE,related_name='corp_sectors',null=True,default=None,blank=True )
    unions = models.ForeignKey('Union', on_delete=models.CASCADE,related_name='union_sectors',null=True,default=None,blank=True )
    def __str__(self):
        return f"""{self.type} sector of {self.region}:
        Corporations: {self.corporations}
        Unions: {self.unions}
        """

class Paramilitary(models.Model):
    name = models.CharField(max_length=50)
    country = models.ForeignKey('Country', on_delete=models.CASCADE,related_name='paramilitaries')
    type = models.CharField(max_length=20,choices=paramilitary_types)
    class Meta:
        verbose_name_plural = "Paramilitaries"
    def __str__(self):
        return f"""The {self.type} {self.name} force in {self.country}:"""

class Account(models.Model):
    owner = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,related_name='player_accounts')
    character_name = models.CharField(max_length=50)
    region = models.ForeignKey('Region', on_delete=models.CASCADE,related_name='region_players')
    corporation = models.ForeignKey('Corporation', on_delete=models.CASCADE,related_name='ceo',null=True,default=None,blank=True )
    paramilitary = models.ForeignKey('Paramilitary', on_delete=models.CASCADE,related_name='military_leader',null=True,default=None,blank=True )
    union = models.ForeignKey('Union', on_delete=models.CASCADE,related_name='union_boss',null=True,default=None,blank=True )
    party = models.ForeignKey('Party', on_delete=models.CASCADE, related_name='members',null=True,default=None,blank=True )
    assignments = models.ForeignKey('Assignment', on_delete=models.CASCADE, related_name='accounts',null=True,default=None,blank=True )
    class Meta:
        verbose_name_plural = "Accounts"
    def __str__(self):
        return f"""In-game Username: {self.username}\n
        Region: {self.region}\n
        Corporation: {self.corporation}\n
        Paramilitary: {self.paramilitary}\n
        Union: {self.union}\n
        Party: {self.party}
        """

manager/forms.py
from django import forms
from django.forms import widgets
from manager.models import *

class AccountForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = [
            'character_name',
            'region',
            'corporation',
            'paramilitary',
            'union',
            'party',
        ]


#Add more fields!
class UnionForm(forms.ModelForm):
    class Meta:
        model = Union
        fields = ['name']

class ParamilitaryForm(forms.ModelForm):
    class Meta:
        model = Paramilitary
        fields = ['name','country','type']

class CorporationForm(forms.ModelForm):
    class Meta:
        model = Corporation
        fields = ['name','specialization']

class PartyForm(forms.ModelForm):
    class Meta:
        model = Party
        fields = ['name','country']

class AssignmentForm(forms.ModelForm):
    class Meta:
        model = Assignment
        fields = ['name','content']

manager/views.py
from django.http import request
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from manager.models import *
from manager.forms import *
from django.contrib.auth import get_user_model

# Create your views here.

def index(request):
    data = {
            "page_title":"Landing Page",
        }
    return render(request,"manager/index.html",data)

def signup_page(request):
    if request.method == "GET":
        data = {
            "form": UserCreationForm(),
            "page_title":"Signup",
        }
        return render(request, "registration/signup.html", context=data)

    elif request.method == "POST":
        form = UserCreationForm(request.POST)
        form.save()
        return redirect("accounts:login")

#Logged in views

@login_required
def home(request):
    data = {
            "page_title":"Home",
        }
    return render(request,'manager/home.html',data)

@login_required
def profile(request):
    print('testtest')
    try:
        print(Account.objects.all())
        print(request.user)
        accounts = Account.objects.all().filter(owner=request.user)
        print(accounts)
    except:
        return redirect("manager:create_profile")
    data = {
            "page_title":"Profile",
            "item": accounts,
        }
    return render(request,'manager/item_detail.html',data)

@login_required
def edit_profile(request):
    return render(request,'manager/home.html')

@login_required
def create_profile(request):
    if request.method == "GET":
        data = {
            "name": "Profile",
            "form": AccountForm(),
            "page_title":"Create Account",
        }
        return render(request, "manager/create_item.html", context=data)

    elif request.method == "POST":
        form = AccountForm(request.POST)
        new_account = form.save(commit=False)
        new_account.owner = request.user
        new_account.save()
        return redirect("manager:home")

@login_required
def create_union(request):
    if request.method == "GET":
        data = {
            "name": "Union",
            "form": UnionForm(),
            "page_title":"Create Union",
        }
        return render(request, "manager/create_item.html", context=data)

    elif request.method == "POST":
        form = UnionForm(request.POST)
        form.save()
        return redirect("manager:profile")

@login_required
def create_party(request):
    if request.method == "GET":
        data = {
            "name": "Party",
            "form": PartyForm(),
            "page_title":"Create Union",
        }
        return render(request, "manager/create_item.html", context=data)

    elif request.method == "POST":
        form = PartyForm(request.POST)
        form.save()
        return redirect("manager:profile")

@login_required
def create_corporation(request):
    if request.method == "GET":
        data = {
            "name": "Corporation",
            "form": CorporationForm(),
            "page_title":"Create Corp",
        }
        return render(request, "manager/create_item.html", context=data)

    elif request.method == "POST":
        form = CorporationForm(request.POST)
        form.save()
        return redirect("manager:profile")

@login_required
def create_paramilitary(request):
    if request.method == "GET":
        data = {
            "name": "Paramilitary",
            "form": ParamilitaryForm(),
            "page_title":"Create Paramilitary",
        }
        return render(request, "manager/create_item.html", context=data)

    elif request.method == "POST":
        form = ParamilitaryForm(request.POST)
        form.save()
        return redirect("manager:profile")

@login_required
def create_assignment(request):
    if request.method == "GET":
        data = {
            "name": "Assignment",
            "form": AssignmentForm(),
            "page_title":"Create Assignment",
        }
        return render(request, "manager/create_item.html", context=data)

    elif request.method == "POST":
        form = AssignmentForm(request.POST)
        form.save()
        return redirect("manager:profile")

manager/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  <title>
    {{ page_title }}
  </title>
</head>
<body class="bg-light bg-gradient">
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Goon Database: {{ page_title }}</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'manager:home' %}"><button class="btn btn-outline-info">Home</button></a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'manager:profile' %}">View Profile</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Register new...
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="{% url 'manager:create_profile' %}">Account</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="{% url 'manager:create_union' %}">Union</a></li>
              <li><a class="dropdown-item" href="{% url 'manager:create_corporation' %}">Corporation</a></li>
              <li><a class="dropdown-item" href="{% url 'manager:create_paramilitary' %}">Paramilitary</a></li>
              <li><a class="dropdown-item" href="{% url 'manager:create_party' %}">Party</a></li>
              <li><a class="dropdown-item" href="{% url 'manager:create_assignment' %}">Assignment</a></li>
            </ul>
          </li>
        </ul>
        <a href="{% url 'manager:logout' %}">
          <button class="btn btn-outline-danger" type="submit">Logout</button>
        </a>
      </div>
    </div>
  </nav>
  {% block body %}
  {% endblock %}
</body>
</html>

manager/templates/loggedout_base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  <title>
    {{ page_title }}
  </title>
</head>
<body class="bg-light bg-gradient">
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">{{ page_title }}</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'manager:signup' %}">Register</a>
          </li>
        </ul>
        <a href="{% url 'manager:login' %}">
          <button class="btn btn-outline-primary" type="login">Login</button>
        </a>
      </div>
    </div>
  </nav>
  {% block body %}
  {% endblock %}
</body>
</html>